import { GateVerdict, SpecDocument, SpecTask } from '../types';

/**
 * Deterministic PR title/body for a task branch (P3 T-02). Pure functions
 * of the spec task, run identity, and any verdicts recorded so far — the
 * same inputs always produce the same PR text, so resume-created and
 * first-run PRs are indistinguishable.
 */
export const prTitle = (runId: string, task: SpecTask): string =>
  `sdlc(${runId}): ${task.id} ${task.title}`;

export const prBody = (
  spec: SpecDocument,
  task: SpecTask,
  runId: string,
  branch: string,
  verdicts: GateVerdict[]
): string => {
  const lines: string[] = [
    '## Summary',
    '',
    `Machine-generated implementation of **${task.id} — ${task.title}**`,
    `from spec \`${spec.id}\` (${spec.prdId}, phase ${spec.phase}).`,
    '',
    `- Run: \`${runId}\``,
    `- Branch: \`${branch}\``,
    `- Story: ${task.storyId} · Complexity: ${task.complexity}` +
      (task.dependsOn.length > 0
        ? ` · Depends on: ${task.dependsOn.join(', ')}`
        : ''),
    '',
    '## Acceptance criteria',
    ''
  ];
  for (const criterion of task.acceptanceCriteria) {
    lines.push(`- ${criterion}`);
  }

  lines.push('', '## Gate verdicts');
  if (verdicts.length === 0) {
    lines.push(
      '',
      '_Recorded after the machine gates run; see the run Chronicle artifacts._'
    );
  } else {
    lines.push('');
    for (const verdict of verdicts) {
      lines.push(
        `- ${verdict.gate}: **${verdict.outcome}**` +
          (verdict.reasons.length > 0 ? ` — ${verdict.reasons.join('; ')}` : '')
      );
    }
  }

  lines.push(
    '',
    '---',
    `Generated by sdlc-workflow (PRD-0011 Phase 3) · run \`${runId}\` · task \`${task.id}\``
  );
  return lines.join('\n');
};
